# Generated by Django 5.0.1 on 2024-02-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErpLinkToken',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('link_token', models.CharField(max_length=255)),
                ('account_token', models.CharField(max_length=255)),
                ('integration_name', models.CharField(max_length=255)),
                ('magic_link_url', models.CharField(max_length=255)),
                ('categories', models.JSONField()),
                ('platform', models.CharField(max_length=255)),
                ('end_user_email_address', models.EmailField(max_length=254)),
                ('end_user_organization_name', models.CharField(max_length=255)),
                ('link_expiry_mins', models.IntegerField()),
                ('should_create_magic_link_url', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_link_token',
            },
        ),
    ]
